// <auto-generated />
using System;
using BuddhaTerapiasAPI.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BuddhaTerapias_API.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20190217185041_UserUpdateTable")]
    partial class UserUpdateTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("BuddhaTerapiasAPI.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<DateTime>("Birthday");

                    b.Property<char>("CivilStatus");

                    b.Property<string>("DateOfBirth");

                    b.Property<string>("Email");

                    b.Property<char>("Gender");

                    b.Property<int>("MobilePhone")
                        .HasMaxLength(9);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Nif")
                        .HasMaxLength(9);

                    b.Property<string>("Observation");

                    b.Property<string>("Profession");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("BuddhaTerapiasAPI.Models.Dev", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<char>("Gender");

                    b.Property<int>("MobilePhone")
                        .HasMaxLength(9);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("BuddhaTerapiasAPI.Models.Therapist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Email");

                    b.Property<char>("Gender");

                    b.Property<int>("MobilePhone")
                        .HasMaxLength(9);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Therapists");
                });
#pragma warning restore 612, 618
        }
    }
}
